#!/bin/sh
chmod +x /usr/bin/iicalc
pip3 install -r /usr/share/iicalc/requirements.txt
gcc -v 1> /dev/null 2> /dev/null
if [ "$?" == "0" ]
then
	pip3 install python-Levenshtein
fi
echo "Updating MIME type Databse..."
update-mime-database /usr/share/mime
