#!/bin/sh
if ! type "python3" > /dev/null; then
	echo "ImaginaryInfinity Calculator requires Python 3 to run. Please install it before attempting to start the calculator."
fi
cd "$(dirname "$0")"
exec ./usr/bin/iicalc