name: Create tag

on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        run: |
          echo 'LATEST_TAG=$(python3 -c "from packaging import version; import subprocess; tag = subprocess.Popen((\"git\", \"tag\"), stdout=subprocess.PIPE); output = subprocess.check_output((\"tail\", \"-1\"), stdin=tag.stdout); tag.wait(); latest_tag = version.parse(output.decode().strip()[1:]); latest = version.parse(subprocess.check_output((\"cat\", \"system/version.txt\")).decode().strip()); print(latest > latest_tag)")' >> $GITHUB_ENV
          echo 'LATEST_VERSION=v$(cat system/version.txt | xargs | tr --delete v)' >> $GITHUB_ENV
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3

        if: ${{ env.LATEST_TAG == 'False' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.LATEST_VERSION }}
